### ISSUE TITLE
tooltips

### ISSUE THREAD

**Issue by polygraph-umg** [the-pudding/same-name#71]
this would be a desktop only feature, so not as pressing. currently all the info is in a table below. some options:

* plain language takeaway on county hover: "In Berkshire County, saying Portland probably refers to Portland, CT"
* top 2 county scores

**Comment by russellsamora** [comment]
* michelle: plain language tooltip - "if you are in in X county you probably mean Y, but maybe Z too"

**Comment by iblind** [comment]
I'd like a tooltip cause I don't know which county's which, but then again, since I don't know, I probably don't _really_ care all that much — just curiosity in the moment. People who live in a county will probably know which county's theirs. The one thing that I'd flag is that if you're interested in your county in particular, it could be interesting to build a quick way of finding out what all these town names refer to in their county specifically (ie isolate the county for easier visual consumption), but again, hardly a requirement — all is pretty clear on the map for me.

**Comment by russellsamora** [comment]
jd: I’m craving some sort of interaction on the map, especially because you have the rankings in the second table, but I can’t see them in the same screen and then I don’t know where all of these counties are. A county tooltip with the top 2-3 rankings could be cool. Maybe even a way to hover over the city dots too because I know all place name variations aren’t spelled exactly the same (or are they? maybe mention that in the methods?)
